[general]
import = ["~/.config/alacritty/catppuccin/catppuccin-mocha.toml"]
live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
decorations = "None"
dynamic_padding = false
opacity = 0.85
blur = true
startup_mode = "Maximized"

[window.padding]
x = 25
y = 20

[font]
size = 10.0

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"

[font.bold]
family = "JetBrainsMono NF"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono NF"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono NF"
style = "Italic"


[keyboard]
bindings = [{ key = "F", mods = "Control", action = "ToggleMaximized" },]
