[general]
import = ["~/.config/alacritty/catppuccin/catppuccin-mocha.toml"]
live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
decorations = "None"
dynamic_padding = false
opacity = 0.9
startup_mode = "Maximized"

[window.padding]
x = 25
y = 20

[font]
size = 12.0

[font.bold]
family = "JetbrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetbrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetbrainsMono Nerd Font"
style = "Regular"

[keyboard]
bindings = [{ key = "F", mods = "Control", action = "ToggleMaximized" },]
